"""sessions

Revision ID: 0a2caeea6870
Revises: fff37943e89f
Create Date: 2025-01-19 21:27:43.973849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2caeea6870'
down_revision = 'fff37943e89f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_session', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['current_session'])

    with op.batch_alter_table('lawyers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_session', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['current_session'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lawyers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('current_session')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('current_session')

    # ### end Alembic commands ###
