"""new update

Revision ID: 2d2850fdbb8a
Revises: 0a2caeea6870
Create Date: 2025-01-20 19:54:15.320402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d2850fdbb8a'
down_revision = '0a2caeea6870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint('clients_current_session_key', type_='unique')
        batch_op.drop_column('current_session')

    with op.batch_alter_table('lawyers', schema=None) as batch_op:
        batch_op.drop_constraint('lawyers_current_session_key', type_='unique')
        batch_op.drop_column('current_session')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lawyers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_session', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('lawyers_current_session_key', ['current_session'])

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_session', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('clients_current_session_key', ['current_session'])

    # ### end Alembic commands ###
