"""empty message

Revision ID: 65337a2b7950
Revises: b985e75c8a73
Create Date: 2025-01-19 01:32:25.588119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65337a2b7950'
down_revision = 'b985e75c8a73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lawyers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bar_number', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['bar_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lawyers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('bar_number')

    # ### end Alembic commands ###
