"""empty message

Revision ID: d610430aa9c4
Revises: d3359403a682
Create Date: 2025-01-03 02:54:45.626642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd610430aa9c4'
down_revision = 'd3359403a682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('areaOfNeed', sa.String(), nullable=False))

    with op.batch_alter_table('lawyers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('specialty', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('barNumber', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('lawFirm', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('professionalExperience', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('credentials', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['photo'])
        batch_op.create_unique_constraint(None, ['barNumber'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lawyers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('credentials')
        batch_op.drop_column('professionalExperience')
        batch_op.drop_column('lawFirm')
        batch_op.drop_column('barNumber')
        batch_op.drop_column('specialty')
        batch_op.drop_column('photo')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('areaOfNeed')

    # ### end Alembic commands ###
